stages:
  - build
  - deploy

docker-build:
  image: docker:cli
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:latest"
        docker push "$CI_REGISTRY_IMAGE:latest"
      fi
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile

deploy:
  image: google/cloud-sdk:latest
  stage: deploy
  variables:
    PRODUCTION_ENV_FILE: $PRODUCTION_ENV_FILE
  script:
    - echo "Cargando variables desde el archivo .env"
    - |
      # Verifica que la variable PRODUCTION_ENV_FILE esté correctamente configurada
      if [ -z "$PRODUCTION_ENV_FILE" ]; then
        echo "La variable PRODUCTION_ENV_FILE no está definida correctamente."
        exit 1
      fi
      # Asegúrate de que el valor de PRODUCTION_ENV_FILE es adecuado
      echo "Contenido de PRODUCTION_ENV_FILE: $PRODUCTION_ENV_FILE"
      
      # Genera el archivo .env correctamente
      echo "$PRODUCTION_ENV_FILE" > .env
      cat .env  # Verifica el contenido del archivo .env generado

    - set -a
    - source .env
    - set +a

    # Asegúrate de que la clave privada esté en formato adecuado (base64-decoding)
    - echo $GCLOUD_SERVICE_KEY | base64 -d > key.json

    # Autenticación en Google Cloud con la clave decodificada
    - gcloud auth activate-service-account --key-file=key.json

    # Configuración de GCloud
    - gcloud config set project $FIREBASE_PROJECT_ID
    - gcloud config set run/region $FIREBASE_UNIVERSE_DOMAIN

    # Construcción y despliegue a Google Cloud Run
    - gcloud builds submit --tag gcr.io/$FIREBASE_PROJECT_ID/umhbackend
    - gcloud run deploy umhbackend \
        --image gcr.io/$FIREBASE_PROJECT_ID/umhbackend \
        --platform managed \
        --region $FIREBASE_UNIVERSE_DOMAIN \
        --allow-unauthenticated
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  environment:
    name: production
